export type PlanStatus = "pending" | "in_progress" | "done" | "blocked";
export type PlanKind = "task" | "buffer";

export interface PlanItem {
  id: string;
  dayId: "sat" | "sun" | "mon" | "tue";
  date: string;
  dayLabel: string;
  phase: string;
  time: string;
  durationMinutes: number;
  title: string;
  criteria: string;
  kind: PlanKind;
  status: PlanStatus;
  progress: number;
  note: string;
}

export const PLAN_VERSION = "2026-09-05-v1";
export const PLAN_SOURCE = "docs/PLAN_UNTIL_TUESDAY.md";
export const PLAN_DEADLINE = "2026-09-08T12:00:00+09:00";

export const dayMilestones = {
  sat: "Supabase 연결, 스키마 생성, 테스트 행 저장",
  sun: "조건 입력 → 법령·의무 도출 → 새로고침 후 유지",
  mon: "점검·보완·총괄 집계와 Release Candidate",
  tue: "동일 대본 2회 연속 성공 및 최종 동결",
} as const;

export const initialPlanItems: PlanItem[] = [
  {
    id: "sat-01",
    dayId: "sat",
    date: "2026-09-05",
    dayLabel: "토요일",
    phase: "기반 구축",
    time: "21:00~21:30",
    durationMinutes: 30,
    title: "시연 범위 동결",
    criteria:
      "활성 화면, 활성 버튼, 역할 3개, 대표 대상 1개, 비교 대상 2개를 한 장에 확정한다. 결재, 엑셀, 관리자, 전체 통계는 제외 목록으로 잠근다.",
    kind: "task",
    status: "done",
    progress: 100,
    note: "대표 7개 라우트와 역할 3개 확정",
  },
  {
    id: "sat-02",
    dayId: "sat",
    date: "2026-09-05",
    dayLabel: "토요일",
    phase: "기반 구축",
    time: "21:30~22:00",
    durationMinutes: 30,
    title: "시연 대본 역산",
    criteria:
      "대시보드 → 대상 선택 → 조건 판정 → 의무 저장 → 증빙 → 보완필요 → 보완 → 이행완료 → 집계 순서를 URL과 버튼 단위로 적는다.",
    kind: "task",
    status: "done",
    progress: 100,
    note: "대시보드→판정→증빙→점검→집계 폐쇄 루프 확정",
  },
  {
    id: "sat-03",
    dayId: "sat",
    date: "2026-09-05",
    dayLabel: "토요일",
    phase: "기반 구축",
    time: "22:00~22:30",
    durationMinutes: 30,
    title: "프로젝트·환경 정리",
    criteria:
      "개발 브랜치, 환경변수 예시, 실행 명령, Supabase 프로젝트 연결 정보를 정리한다. 비밀키는 저장소에 넣지 않는다.",
    kind: "task",
    status: "done",
    progress: 100,
    note: "Git, Netlify, 공개 환경변수, Windows 경로 정리",
  },
  {
    id: "sat-04",
    dayId: "sat",
    date: "2026-09-05",
    dayLabel: "토요일",
    phase: "기반 구축",
    time: "22:30~23:15",
    durationMinutes: 45,
    title: "DB 스키마 1차 작성",
    criteria:
      "ref_*, target, target_applicability, compliance_record, evidence, inspection_*, audit_event 테이블과 기본 인덱스를 마이그레이션으로 만든다.",
    kind: "task",
    status: "done",
    progress: 100,
    note: "핵심 테이블·인덱스 원격 적용",
  },
  {
    id: "sat-05",
    dayId: "sat",
    date: "2026-09-05",
    dayLabel: "토요일",
    phase: "기반 구축",
    time: "23:15~23:40",
    durationMinutes: 25,
    title: "Storage·권한 기반 설정",
    criteria:
      "비공개 증빙 버킷을 만들고 업로드·조회 정책의 기본 틀을 적용한다. 브라우저에 서비스 키가 포함되지 않았음을 확인한다.",
    kind: "task",
    status: "done",
    progress: 100,
    note: "비공개 버킷·RLS·10MB 제한 적용",
  },
  {
    id: "sat-06",
    dayId: "sat",
    date: "2026-09-05",
    dayLabel: "토요일",
    phase: "기반 구축",
    time: "23:40~24:00",
    durationMinutes: 20,
    title: "연결 스모크 테스트",
    criteria:
      "테스트 대상 1건을 생성·조회·수정·삭제하고, 앱에서 Supabase 왕복이 되는지 확인한다. 실패한 상태로 UI 개발에 들어가지 않는다.",
    kind: "task",
    status: "done",
    progress: 100,
    note: "Target CRUD·Storage·감사로그 통과",
  },
  {
    id: "sun-01",
    dayId: "sun",
    date: "2026-09-06",
    dayLabel: "일요일",
    phase: "법령 DB·판정",
    time: "09:00~09:30",
    durationMinutes: 30,
    title: "전일 상태 재검증",
    criteria:
      "빈 환경에서 마이그레이션을 다시 실행하고 테스트 행 저장을 확인한다. 오류가 있으면 10:00 전까지 우선 수정한다.",
    kind: "task",
    status: "done",
    progress: 100,
    note: "원격 readiness·빌드 재검증 완료",
  },
  {
    id: "sun-02",
    dayId: "sun",
    date: "2026-09-06",
    dayLabel: "일요일",
    phase: "법령 DB·판정",
    time: "09:30~10:30",
    durationMinutes: 60,
    title: "핵심 법령 선정 기준 적용",
    criteria:
      "중대재해처벌법, 산업안전보건법, 시설물안전법을 우선 포함한다. 대표 시나리오와 직접 연결되는 법령 및 참조 법령을 더해 총 50~150개 목록을 확정한다.",
    kind: "task",
    status: "in_progress",
    progress: 75,
    note: "80건 축소 투영 검증, 최종 승인 목록 보완 필요",
  },
  {
    id: "sun-03",
    dayId: "sun",
    date: "2026-09-06",
    dayLabel: "일요일",
    phase: "법령 DB·판정",
    time: "10:30~11:30",
    durationMinutes: 60,
    title: "축소 ETL 작성",
    criteria:
      "원본 CSV에서 선택 법령과 관련 문서·조문·의무·연결만 추출한다. law_id, unit_id, rul_id, obl_id, 원천 버전을 그대로 보존한다.",
    kind: "task",
    status: "done",
    progress: 100,
    note: "RDB·그래프 호환 투영 스크립트 검증",
  },
  {
    id: "sun-04",
    dayId: "sun",
    date: "2026-09-06",
    dayLabel: "일요일",
    phase: "법령 DB·판정",
    time: "11:30~12:00",
    durationMinutes: 30,
    title: "축소 데이터 검증",
    criteria:
      "고아 외래키 0건, 중복 기본키 0건, 선택 법령 수 50~150개를 확인한다. 건수 검증 결과를 로그로 남긴다.",
    kind: "task",
    status: "done",
    progress: 100,
    note: "80개 법령 투영과 참조 구조 검증",
  },
  {
    id: "sun-05",
    dayId: "sun",
    date: "2026-09-06",
    dayLabel: "일요일",
    phase: "법령 DB·판정",
    time: "12:00~13:00",
    durationMinutes: 60,
    title: "점심 및 버퍼",
    criteria:
      "오전 블로커가 있으면 이 시간에만 흡수한다. 범위는 늘리지 않는다.",
    kind: "buffer",
    status: "pending",
    progress: 0,
    note: "일정 완충 구간이며 전체 진행률 계산에서 제외",
  },
  {
    id: "sun-06",
    dayId: "sun",
    date: "2026-09-06",
    dayLabel: "일요일",
    phase: "법령 DB·판정",
    time: "13:00~14:00",
    durationMinutes: 60,
    title: "규칙 허용목록 검수",
    criteria:
      "화면에 사용할 규칙 8~12개의 조건 항목·연산자·값·단위·인용문·도출 의무를 원문과 대조한다. demo_approved = true를 부여한다.",
    kind: "task",
    status: "in_progress",
    progress: 50,
    note: "원격 4개 승인 규칙, 목표 8~12개",
  },
  {
    id: "sun-07",
    dayId: "sun",
    date: "2026-09-06",
    dayLabel: "일요일",
    phase: "법령 DB·판정",
    time: "14:00~14:40",
    durationMinutes: 40,
    title: "시나리오 시드 작성",
    criteria:
      "역할 3개, 대표 대상 1개, 비교 대상 2개, 초기 이행 상태를 재현 가능한 시드 파일로 만든다. 실제 확정 자료가 아니면 대상명에 (시연)을 표시한다.",
    kind: "task",
    status: "done",
    progress: 100,
    note: "역할 3개·대상 3개·의무·점검 시드 적용",
  },
  {
    id: "sun-08",
    dayId: "sun",
    date: "2026-09-06",
    dayLabel: "일요일",
    phase: "법령 DB·판정",
    time: "14:40~15:30",
    durationMinutes: 50,
    title: "판정 함수 구현",
    criteria:
      "대상 속성을 읽어 gte, gt, lte, lt 규칙을 결정적으로 평가한다. 미승인 규칙은 결과에 포함하지 않는다.",
    kind: "task",
    status: "in_progress",
    progress: 60,
    note: "규칙 스냅숏 12건 저장, 입력 UI 연계 필요",
  },
  {
    id: "sun-09",
    dayId: "sun",
    date: "2026-09-06",
    dayLabel: "일요일",
    phase: "법령 DB·판정",
    time: "15:30~16:30",
    durationMinutes: 60,
    title: "공통 UI 셸 구현",
    criteria:
      "연녹색 TopBanner, 검정 GNB, 용인시 표기 영역, LNB, 본문, Footer를 공통 컴포넌트로 구현한다. 데스크톱 1440px 이상을 우선한다.",
    kind: "task",
    status: "done",
    progress: 100,
    note: "용인시 브랜드 셸과 역할 전환 구현",
  },
  {
    id: "sun-10",
    dayId: "sun",
    date: "2026-09-06",
    dayLabel: "일요일",
    phase: "법령 DB·판정",
    time: "16:30~17:30",
    durationMinutes: 60,
    title: "법령 목록·검색 화면",
    criteria:
      "법령명과 내용 검색, 법령구분 필터, 법령 목록과 근거 조문 상세가 DB에서 조회된다. 검색 결과를 화면에 하드코딩하지 않는다.",
    kind: "task",
    status: "done",
    progress: 100,
    note: "Supabase ref_law 원격 조회 확인",
  },
  {
    id: "sun-11",
    dayId: "sun",
    date: "2026-09-06",
    dayLabel: "일요일",
    phase: "법령 DB·판정",
    time: "17:30~18:00",
    durationMinutes: 30,
    title: "관리대상 선택 화면",
    criteria:
      "대표 대상과 비교 대상이 DB에서 로드되고 대표 대상을 선택할 수 있다.",
    kind: "task",
    status: "in_progress",
    progress: 70,
    note: "화면 구현 완료, 원격 target 연계 필요",
  },
  {
    id: "sun-12",
    dayId: "sun",
    date: "2026-09-06",
    dayLabel: "일요일",
    phase: "법령 DB·판정",
    time: "18:00~19:00",
    durationMinutes: 60,
    title: "저녁 및 버퍼",
    criteria: "데이터 적재 오류 또는 UI 셸 오류를 정리한다.",
    kind: "buffer",
    status: "pending",
    progress: 0,
    note: "일정 완충 구간이며 전체 진행률 계산에서 제외",
  },
  {
    id: "sun-13",
    dayId: "sun",
    date: "2026-09-06",
    dayLabel: "일요일",
    phase: "법령 DB·판정",
    time: "19:00~20:00",
    durationMinutes: 60,
    title: "적용조건 입력 화면",
    criteria:
      "대표 대상의 시설 유형·규모 등 시연 조건을 입력하고 저장할 수 있다. 입력값 변경 시 재판정할 수 있다.",
    kind: "task",
    status: "in_progress",
    progress: 20,
    note: "대상 속성 UI·재판정 연결 필요",
  },
  {
    id: "sun-14",
    dayId: "sun",
    date: "2026-09-06",
    dayLabel: "일요일",
    phase: "법령 DB·판정",
    time: "20:00~21:00",
    durationMinutes: 60,
    title: "적용 법령·의무 결과 화면",
    criteria:
      "판정 결과에 법령명, 조문, 인용문, 의무명, 판정 이유를 표시한다. 입력 조건과 규칙 버전을 스냅숏으로 저장한다.",
    kind: "task",
    status: "in_progress",
    progress: 40,
    note: "화면 구조 구현, 원격 판정 연결 필요",
  },
  {
    id: "sun-15",
    dayId: "sun",
    date: "2026-09-06",
    dayLabel: "일요일",
    phase: "법령 DB·판정",
    time: "21:00~22:00",
    durationMinutes: 60,
    title: "법 의무사항·이행시기 화면",
    criteria:
      "도출된 의무 8~12개를 계층형 표로 보여주고 월 또는 상·하반기 값을 저장한다.",
    kind: "task",
    status: "in_progress",
    progress: 70,
    note: "화면·로컬 저장 완료, Supabase 쓰기 연결 필요",
  },
  {
    id: "sun-16",
    dayId: "sun",
    date: "2026-09-06",
    dayLabel: "일요일",
    phase: "법령 DB·판정",
    time: "22:00~22:30",
    durationMinutes: 30,
    title: "새로고침 영속성 테스트",
    criteria:
      "조건, 판정 결과, 의무, 이행시기가 새로고침과 재접속 후에도 유지되는지 확인한다.",
    kind: "task",
    status: "in_progress",
    progress: 40,
    note: "로컬 영속화 통과, 업무 DB 영속화 필요",
  },
  {
    id: "sun-17",
    dayId: "sun",
    date: "2026-09-06",
    dayLabel: "일요일",
    phase: "법령 DB·판정",
    time: "22:30~23:00",
    durationMinutes: 30,
    title: "초기화 경로 구현",
    criteria:
      "한 번의 시드 재적재 또는 관리자 명령으로 시연 초기 상태를 복구한다. 초기화 소요시간은 2분 이내를 목표로 한다.",
    kind: "task",
    status: "in_progress",
    progress: 50,
    note: "클라이언트 초기화 구현, DB 시드 초기화 필요",
  },
  {
    id: "mon-01",
    dayId: "mon",
    date: "2026-09-07",
    dayLabel: "월요일",
    phase: "증빙·점검·동결",
    time: "09:00~09:30",
    durationMinutes: 30,
    title: "일요일 결과 스모크 테스트",
    criteria:
      "초기화 → 조건 입력 → 판정 → 의무 저장을 처음부터 다시 수행한다. 오전 첫 30분에 전일 회귀 오류를 찾는다.",
    kind: "task",
    status: "in_progress",
    progress: 30,
    note: "DB 기반 테스트 통과, 전체 시연 루프 미완료",
  },
  {
    id: "mon-02",
    dayId: "mon",
    date: "2026-09-07",
    dayLabel: "월요일",
    phase: "증빙·점검·동결",
    time: "09:30~10:30",
    durationMinutes: 60,
    title: "의무이행 기록 화면",
    criteria:
      "의무별 조치일자, 상태, 비고를 저장한다. 상태 문자열은 이행완료, 보완필요, 미이행, 해당없음으로 고정한다.",
    kind: "task",
    status: "in_progress",
    progress: 60,
    note: "UI·상태 모델 완료, 원격 CRUD 필요",
  },
  {
    id: "mon-03",
    dayId: "mon",
    date: "2026-09-07",
    dayLabel: "월요일",
    phase: "증빙·점검·동결",
    time: "10:30~11:30",
    durationMinutes: 60,
    title: "증빙 업로드 백엔드",
    criteria:
      "실제 파일을 비공개 Storage에 업로드하고 파일 메타데이터를 evidence에 저장한다. 파일 크기와 소유 기록을 남긴다.",
    kind: "task",
    status: "in_progress",
    progress: 50,
    note: "Storage 왕복 검증, 화면 메타데이터 연결 필요",
  },
  {
    id: "mon-04",
    dayId: "mon",
    date: "2026-09-07",
    dayLabel: "월요일",
    phase: "증빙·점검·동결",
    time: "11:30~12:00",
    durationMinutes: 30,
    title: "증빙 다운로드·삭제",
    criteria:
      "등록한 파일의 다운로드와 삭제가 동작한다. 미리보기는 여유가 있을 때만 구현한다.",
    kind: "task",
    status: "in_progress",
    progress: 50,
    note: "API 왕복 검증, 화면 연결 필요",
  },
  {
    id: "mon-05",
    dayId: "mon",
    date: "2026-09-07",
    dayLabel: "월요일",
    phase: "증빙·점검·동결",
    time: "12:00~13:00",
    durationMinutes: 60,
    title: "점심 및 버퍼",
    criteria: "증빙 접근권한 문제를 이 시간 안에 해결한다.",
    kind: "buffer",
    status: "pending",
    progress: 0,
    note: "일정 완충 구간이며 전체 진행률 계산에서 제외",
  },
  {
    id: "mon-06",
    dayId: "mon",
    date: "2026-09-07",
    dayLabel: "월요일",
    phase: "증빙·점검·동결",
    time: "13:00~14:00",
    durationMinutes: 60,
    title: "의무이행 UI 완성",
    criteria:
      "법령명·조문·법령내용은 읽기 전용으로, 조치일자·증빙·비고는 편집 가능하게 구성한다.",
    kind: "task",
    status: "in_progress",
    progress: 60,
    note: "읽기·편집 UI 구현, 원격 저장 필요",
  },
  {
    id: "mon-07",
    dayId: "mon",
    date: "2026-09-07",
    dayLabel: "월요일",
    phase: "증빙·점검·동결",
    time: "14:00~15:00",
    durationMinutes: 60,
    title: "점검 회차·범위 생성",
    criteria:
      "비교 대상 3개와 의무 8~12개를 포함하는 점검 회차를 생성한다. 선택 대상과 항목이 후속 화면 범위를 결정한다.",
    kind: "task",
    status: "in_progress",
    progress: 60,
    note: "원격 회차 1개·범위 30건 시드",
  },
  {
    id: "mon-08",
    dayId: "mon",
    date: "2026-09-07",
    dayLabel: "월요일",
    phase: "증빙·점검·동결",
    time: "15:00~16:00",
    durationMinutes: 60,
    title: "점검 화면 구현",
    criteria:
      "점검자는 상태와 점검내용만 수정한다. 대상, 이행일자, 증빙은 읽기 전용으로 표시한다.",
    kind: "task",
    status: "in_progress",
    progress: 60,
    note: "UI 구현 완료, 원격 수정 필요",
  },
  {
    id: "mon-09",
    dayId: "mon",
    date: "2026-09-07",
    dayLabel: "월요일",
    phase: "증빙·점검·동결",
    time: "16:00~16:40",
    durationMinutes: 40,
    title: "보완 요구 생성",
    criteria:
      "보완필요 저장 시 담당자에게 보완할 항목과 점검내용이 나타나고 감사 이벤트가 기록된다.",
    kind: "task",
    status: "in_progress",
    progress: 30,
    note: "상태 흐름 UI 존재, 원격 알림·감사 연계 필요",
  },
  {
    id: "mon-10",
    dayId: "mon",
    date: "2026-09-07",
    dayLabel: "월요일",
    phase: "증빙·점검·동결",
    time: "16:40~17:30",
    durationMinutes: 50,
    title: "담당자 보완 제출",
    criteria:
      "기존 증빙 이력을 유지하면서 새 증빙을 추가하고 재제출할 수 있다. 최신 제출과 이전 이력을 구분한다.",
    kind: "task",
    status: "in_progress",
    progress: 30,
    note: "UI 흐름 존재, 증빙 버전 저장 필요",
  },
  {
    id: "mon-11",
    dayId: "mon",
    date: "2026-09-07",
    dayLabel: "월요일",
    phase: "증빙·점검·동결",
    time: "17:30~18:00",
    durationMinutes: 30,
    title: "재점검 완료",
    criteria:
      "점검자가 동일 항목을 이행완료로 바꾸고 변경 전후 상태와 시각이 남는다.",
    kind: "task",
    status: "in_progress",
    progress: 30,
    note: "UI 흐름 존재, 변경이력 영속화 필요",
  },
  {
    id: "mon-12",
    dayId: "mon",
    date: "2026-09-07",
    dayLabel: "월요일",
    phase: "증빙·점검·동결",
    time: "18:00~19:00",
    durationMinutes: 60,
    title: "저녁 및 버퍼",
    criteria: "19:00 이후에는 신규 화면을 추가하지 않는다.",
    kind: "buffer",
    status: "pending",
    progress: 0,
    note: "일정 완충 구간이며 전체 진행률 계산에서 제외",
  },
  {
    id: "mon-13",
    dayId: "mon",
    date: "2026-09-07",
    dayLabel: "월요일",
    phase: "증빙·점검·동결",
    time: "19:00~20:00",
    durationMinutes: 60,
    title: "총괄표·이행률 계산",
    criteria:
      "O/△/X/- 행렬, 항목별 건수, 대상별 이행률을 저장된 점검 결과에서 계산한다. 해당없음은 모수에서 제외한다.",
    kind: "task",
    status: "in_progress",
    progress: 60,
    note: "UI 계산 완료, 원격 점검 결과 기반 전환 필요",
  },
  {
    id: "mon-14",
    dayId: "mon",
    date: "2026-09-07",
    dayLabel: "월요일",
    phase: "증빙·점검·동결",
    time: "20:00~20:40",
    durationMinutes: 40,
    title: "대시보드 최소 위젯",
    criteria:
      "대상 수, 이행완료·보완필요·미이행 건수, 전체 이행률만 집계 뷰에서 표시한다.",
    kind: "task",
    status: "in_progress",
    progress: 60,
    note: "위젯 구현 완료, 원격 집계 전환 필요",
  },
  {
    id: "mon-15",
    dayId: "mon",
    date: "2026-09-07",
    dayLabel: "월요일",
    phase: "증빙·점검·동결",
    time: "20:40~21:20",
    durationMinutes: 40,
    title: "역할 전환·접근범위 검증",
    criteria:
      "담당자, 실·국 점검자, 경영책임자 관점에서 노출 화면과 편집 가능 필드를 확인한다. 데모용 단순화가 있으면 코드와 대본에 표시한다.",
    kind: "task",
    status: "in_progress",
    progress: 70,
    note: "역할 UI·RLS 구현, 실제 Auth 바인딩 제외",
  },
  {
    id: "mon-16",
    dayId: "mon",
    date: "2026-09-07",
    dayLabel: "월요일",
    phase: "증빙·점검·동결",
    time: "21:20~21:50",
    durationMinutes: 30,
    title: "시연 외 UI 차단",
    criteria:
      "동작하지 않는 메뉴와 버튼을 숨기거나 비활성화한다. 클릭 가능한데 반응이 없는 요소를 0개로 만든다.",
    kind: "task",
    status: "in_progress",
    progress: 80,
    note: "대부분 비활성화, 최종 클릭 점검 필요",
  },
  {
    id: "mon-17",
    dayId: "mon",
    date: "2026-09-07",
    dayLabel: "월요일",
    phase: "증빙·점검·동결",
    time: "21:50~22:20",
    durationMinutes: 30,
    title: "용인시 표기·시각 정리",
    criteria:
      "서울시·대구시·OO광역시 예시값을 제거한다. 폰트, 표 너비, 상태색, 버튼 정렬을 시연 해상도에서 점검한다.",
    kind: "task",
    status: "done",
    progress: 100,
    note: "공식 로고·마젠타·퍼플·청록 팔레트 적용",
  },
  {
    id: "mon-18",
    dayId: "mon",
    date: "2026-09-07",
    dayLabel: "월요일",
    phase: "증빙·점검·동결",
    time: "22:20~22:40",
    durationMinutes: 20,
    title: "전체 E2E 1차",
    criteria:
      "초기화부터 대시보드 갱신까지 시연 대본 전체를 중단 없이 실행하고 시간을 측정한다.",
    kind: "task",
    status: "pending",
    progress: 0,
    note: "",
  },
  {
    id: "mon-19",
    dayId: "mon",
    date: "2026-09-07",
    dayLabel: "월요일",
    phase: "증빙·점검·동결",
    time: "22:40~23:00",
    durationMinutes: 20,
    title: "Release Candidate 생성",
    criteria:
      "성공 커밋 또는 체크포인트, DB 시드, 마이그레이션, 환경 설정 목록, 배포 URL을 고정한다. 23:00 기능 동결을 선언한다.",
    kind: "task",
    status: "in_progress",
    progress: 30,
    note: "현재 체크포인트 존재, 기능 동결 전",
  },
  {
    id: "tue-01",
    dayId: "tue",
    date: "2026-09-08",
    dayLabel: "화요일",
    phase: "리허설·최종 동결",
    time: "08:30~09:00",
    durationMinutes: 30,
    title: "환경·배포 상태 확인",
    criteria:
      "배포 URL, Supabase 연결, Storage 업로드, 브라우저 해상도, 네트워크 상태를 확인한다. 초기 시드로 리셋한다.",
    kind: "task",
    status: "pending",
    progress: 0,
    note: "",
  },
  {
    id: "tue-02",
    dayId: "tue",
    date: "2026-09-08",
    dayLabel: "화요일",
    phase: "리허설·최종 동결",
    time: "09:00~09:40",
    durationMinutes: 40,
    title: "리허설 1회차",
    criteria:
      "설명을 포함해 실제 영업 대본대로 실행한다. 클릭 실수와 설명 시간을 포함해 전체 소요시간을 기록한다.",
    kind: "task",
    status: "pending",
    progress: 0,
    note: "",
  },
  {
    id: "tue-03",
    dayId: "tue",
    date: "2026-09-08",
    dayLabel: "화요일",
    phase: "리허설·최종 동결",
    time: "09:40~10:20",
    durationMinutes: 40,
    title: "P0 수정 시간",
    criteria:
      "중단·오판정·저장 실패만 수정한다. 문구·간격·색상 같은 경미한 문제는 수정하지 않는다.",
    kind: "task",
    status: "pending",
    progress: 0,
    note: "",
  },
  {
    id: "tue-04",
    dayId: "tue",
    date: "2026-09-08",
    dayLabel: "화요일",
    phase: "리허설·최종 동결",
    time: "10:20~10:35",
    durationMinutes: 15,
    title: "환경 재초기화",
    criteria:
      "시드 재적재, Storage 시연파일 정리, 브라우저 캐시·세션 확인을 수행한다.",
    kind: "task",
    status: "pending",
    progress: 0,
    note: "",
  },
  {
    id: "tue-05",
    dayId: "tue",
    date: "2026-09-08",
    dayLabel: "화요일",
    phase: "리허설·최종 동결",
    time: "10:35~11:15",
    durationMinutes: 40,
    title: "리허설 2회차",
    criteria:
      "동일 대본을 다시 실행한다. 첫 리허설과 같은 결과가 나오면 기능 합격으로 판정한다.",
    kind: "task",
    status: "pending",
    progress: 0,
    note: "",
  },
  {
    id: "tue-06",
    dayId: "tue",
    date: "2026-09-08",
    dayLabel: "화요일",
    phase: "리허설·최종 동결",
    time: "11:15~11:35",
    durationMinutes: 20,
    title: "복구 패키지 준비",
    criteria:
      "초기화 명령, 마지막 성공 체크포인트, 테스트 증빙파일, URL 북마크, 역할별 시작 화면을 한 폴더에 정리한다.",
    kind: "task",
    status: "pending",
    progress: 0,
    note: "",
  },
  {
    id: "tue-07",
    dayId: "tue",
    date: "2026-09-08",
    dayLabel: "화요일",
    phase: "리허설·최종 동결",
    time: "11:35~12:00",
    durationMinutes: 25,
    title: "최종 동결",
    criteria:
      "신규 배포를 중단하고 시연 직전 DB 상태를 백업한다. 대표 대상은 대본의 시작 상태로 되돌린다.",
    kind: "task",
    status: "pending",
    progress: 0,
    note: "",
  },
];

export function calculateProgress(items: PlanItem[]) {
  const work = items.filter(item => item.kind === "task");
  const weightedTotal = work.reduce(
    (sum, item) => sum + item.durationMinutes,
    0
  );
  const weightedDone = work.reduce(
    (sum, item) => sum + (item.durationMinutes * item.progress) / 100,
    0
  );
  return {
    percent: weightedTotal
      ? Math.round((weightedDone / weightedTotal) * 100)
      : 0,
    completed: work.filter(item => item.status === "done").length,
    inProgress: work.filter(item => item.status === "in_progress").length,
    blocked: work.filter(item => item.status === "blocked").length,
    pending: work.filter(item => item.status === "pending").length,
    total: work.length,
  };
}
